# -*- coding: utf-8 -*-
"""Actividad 3 Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpgPY01W_kOWXh6QrueBeiUnXgjbXFgP
"""

pip install matplotlib

pip install pandas

from matplotlib import pyplot as plt

import numpy as np

import csv

from collections import Counter

import pandas as pd

plt.style.use("fivethirtyeight")

data = pd.read_csv('data.csv')
ids = data['Responder_id']
lang_responses = data['LanguagesWorkedWith']

languaje_counter = Counter()

for response in lang_responses:
    languaje_counter.update(response.split(';'))

languages = []
popularity = []

for item in languaje_counter.most_common(15):
  languages.append(item[0])
  popularity.append(item[1])

languages.reverse()
popularity.reverse()

plt.barh(languages, popularity, color= '#493e63')

#plt.ylabel('Programming Languages')
plt.xlabel('Number of People Who Use', color= '#493e63')
plt.title('Most Popular Languages', color='#493e63')



plt.tight_layout()


plt.show()