# -*- coding: utf-8 -*-
"""Actividad 3 csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18g81F-WAzTSP__Kd6sLTC7ro7KC8Qz95
"""

pip install matplotlib

from matplotlib import pyplot as plt

import numpy as np

import csv

from collections import Counter

plt.style.use("fivethirtyeight")

with open('data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)
  languaje_counter = Counter()

  for row in csv_reader:
    languaje_counter.update(row['LanguagesWorkedWith'].split(';'))

languages = []
popularity = []

for item in languaje_counter.most_common(15):
  languages.append(item[0])
  popularity.append(item[1])

languages.reverse()
popularity.reverse()

plt.barh(languages, popularity, color= '#493e63')

#plt.ylabel('Programming Languages')
plt.xlabel('Number of People Who Use', color= '#391140')
plt.title('Most Popular Languages', color='#493e63')



plt.tight_layout()


plt.show()